name: PR Preview

on:
  pull_request:

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  testnet-bundle-preview:
    if: github.base_ref != 'stable'
    uses: ./.github/workflows/bundle-and-deploy.yml
    with:
      environment: testnet-preview
      near_wallet_env: testnet_STAGING
    secrets: inherit

  mainnet-bundle-preview:
    if: github.base_ref != 'stable'
    uses: ./.github/workflows/bundle-and-deploy.yml
    with:
      environment: mainnet-preview
      near_wallet_env: mainnet_STAGING
    secrets: inherit

  validate-release-pr:
    if: github.base_ref == 'stable'
    uses: ./.github/workflows/bundle-and-deploy.yml
    with:
      deploy_preview: false
      environment: mainnet
      near_wallet_env: mainnet
    secrets: inherit
